// Generated by TootNet.Generator.  DO NOT EDIT!

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Threading.Tasks;
using TootNet.Internal;
using TootNet.Objects;

namespace TootNet.Rest
{
    public class Blocks : ApiBase
    {
        internal Blocks(Tokens e) : base(e) { }

        /// <summary>
        /// <para>View blocked users</para>
        /// <para>Available parameters:</para>
        /// <para>- <c>long</c> max_id (optional)</para>
        /// <para>- <c>long</c> since_id (optional)</para>
        /// <para>- <c>long</c> min_id (optional)</para>
        /// <para>- <c>int</c> limit (optional)</para>
        /// </summary>
        /// <param name="parameters">The parameters.</param>
        /// <returns>
        /// <para>The task object representing the asynchronous operation.</para>
        /// <para>The Result property on the task object returns the list of account object.</para>
        /// </returns>
        public Task<Linked<Objects.Account>> GetAsync(params Expression<Func<string, object>>[] parameters)
        {
            return Tokens.AccessApiAsync<Linked<Objects.Account>>(MethodType.Get, "blocks", Utils.ExpressionToDictionary(parameters));
        }

        /// <inheritdoc cref="GetAsync(Expression{Func{string, object}}[])"/>
        public Task<Linked<Objects.Account>> GetAsync(IDictionary<string, object> parameters)
        {
            return Tokens.AccessApiAsync<Linked<Objects.Account>>(MethodType.Get, "blocks", parameters);
        }

        /// <summary>
        /// <para>Block account</para>
        /// <para>Available parameters:</para>
        /// <para>- <c>long</c> id (required)</para>
        /// </summary>
        /// <param name="parameters">The parameters.</param>
        /// <returns>
        /// <para>The task object representing the asynchronous operation.</para>
        /// <para>The Result property on the task object returns the relationship object.</para>
        /// </returns>
        public Task<Objects.Relationship> BlockAsync(params Expression<Func<string, object>>[] parameters)
        {
            return Tokens.AccessParameterReservedApiAsync<Objects.Relationship>(MethodType.Post, "accounts/{id}/block", "id", Utils.ExpressionToDictionary(parameters));
        }

        /// <inheritdoc cref="BlockAsync(Expression{Func{string, object}}[])"/>
        public Task<Objects.Relationship> BlockAsync(IDictionary<string, object> parameters)
        {
            return Tokens.AccessParameterReservedApiAsync<Objects.Relationship>(MethodType.Post, "accounts/{id}/block", "id", parameters);
        }

        /// <summary>
        /// <para>Unblock account</para>
        /// <para>Available parameters:</para>
        /// <para>- <c>long</c> id (required)</para>
        /// </summary>
        /// <param name="parameters">The parameters.</param>
        /// <returns>
        /// <para>The task object representing the asynchronous operation.</para>
        /// <para>The Result property on the task object returns the relationship object.</para>
        /// </returns>
        public Task<Objects.Relationship> UnblockAsync(params Expression<Func<string, object>>[] parameters)
        {
            return Tokens.AccessParameterReservedApiAsync<Objects.Relationship>(MethodType.Post, "accounts/{id}/unblock", "id", Utils.ExpressionToDictionary(parameters));
        }

        /// <inheritdoc cref="UnblockAsync(Expression{Func{string, object}}[])"/>
        public Task<Objects.Relationship> UnblockAsync(IDictionary<string, object> parameters)
        {
            return Tokens.AccessParameterReservedApiAsync<Objects.Relationship>(MethodType.Post, "accounts/{id}/unblock", "id", parameters);
        }
    }
}
