// Generated by TootNet.Generator.  DO NOT EDIT!

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Threading.Tasks;
using TootNet.Internal;
using TootNet.Objects;

namespace TootNet.Rest
{
    public class Emails : ApiBase
    {
        internal Emails(Tokens e) : base(e) { }

        /// <summary>
        /// <para>Resend confirmation email.</para>
        /// <para>Available parameters:</para>
        /// <para>- <c>string</c> email (If provided, updates the unconfirmed user's email before resending the confirmation email) (optional)</para>
        /// </summary>
        /// <param name="parameters">The parameters.</param>
        /// <returns>
        /// <para>The task object representing the asynchronous operation.</para>
        /// <para>The Result property on the task object returns the empty object.</para>
        /// </returns>
        public Task ConfirmationAsync(params Expression<Func<string, object>>[] parameters)
        {
            return Tokens.AccessApiAsync(MethodType.Post, "emails/confirmation", Utils.ExpressionToDictionary(parameters));
        }

        /// <inheritdoc cref="ConfirmationAsync(Expression{Func{string, object}}[])"/>
        public Task ConfirmationAsync(IDictionary<string, object> parameters)
        {
            return Tokens.AccessApiAsync(MethodType.Post, "emails/confirmation", parameters);
        }
    }
}
