// Generated by TootNet.Generator.  DO NOT EDIT!

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Threading.Tasks;
using TootNet.Internal;
using TootNet.Objects;

namespace TootNet.Rest
{
    public class Endorsements : ApiBase
    {
        internal Endorsements(Tokens e) : base(e) { }

        /// <summary>
        /// <para>View currently featured profiles</para>
        /// <para>Available parameters:</para>
        /// <para>- <c>long</c> max_id (optional)</para>
        /// <para>- <c>long</c> since_id (optional)</para>
        /// <para>- <c>int</c> limit (optional)</para>
        /// </summary>
        /// <param name="parameters">The parameters.</param>
        /// <returns>
        /// <para>The task object representing the asynchronous operation.</para>
        /// <para>The Result property on the task object returns the list of account object.</para>
        /// </returns>
        public Task<Linked<Objects.Account>> GetAsync(params Expression<Func<string, object>>[] parameters)
        {
            return Tokens.AccessApiAsync<Linked<Objects.Account>>(MethodType.Get, "endorsements", Utils.ExpressionToDictionary(parameters));
        }

        /// <inheritdoc cref="GetAsync(Expression{Func{string, object}}[])"/>
        public Task<Linked<Objects.Account>> GetAsync(IDictionary<string, object> parameters)
        {
            return Tokens.AccessApiAsync<Linked<Objects.Account>>(MethodType.Get, "endorsements", parameters);
        }

        /// <summary>
        /// <para>Feature account on your profile</para>
        /// <para>Available parameters:</para>
        /// <para>- <c>long</c> id (required)</para>
        /// </summary>
        /// <param name="parameters">The parameters.</param>
        /// <returns>
        /// <para>The task object representing the asynchronous operation.</para>
        /// <para>The Result property on the task object returns the relationship object.</para>
        /// </returns>
        public Task<Objects.Relationship> PinAsync(params Expression<Func<string, object>>[] parameters)
        {
            return Tokens.AccessParameterReservedApiAsync<Objects.Relationship>(MethodType.Post, "accounts/{id}/pin", "id", Utils.ExpressionToDictionary(parameters));
        }

        /// <inheritdoc cref="PinAsync(Expression{Func{string, object}}[])"/>
        public Task<Objects.Relationship> PinAsync(IDictionary<string, object> parameters)
        {
            return Tokens.AccessParameterReservedApiAsync<Objects.Relationship>(MethodType.Post, "accounts/{id}/pin", "id", parameters);
        }

        /// <summary>
        /// <para>Unfeature account from profile</para>
        /// <para>Available parameters:</para>
        /// <para>- <c>long</c> id (required)</para>
        /// </summary>
        /// <param name="parameters">The parameters.</param>
        /// <returns>
        /// <para>The task object representing the asynchronous operation.</para>
        /// <para>The Result property on the task object returns the relationship object.</para>
        /// </returns>
        public Task<Objects.Relationship> UnpinAsync(params Expression<Func<string, object>>[] parameters)
        {
            return Tokens.AccessParameterReservedApiAsync<Objects.Relationship>(MethodType.Post, "accounts/{id}/unpin", "id", Utils.ExpressionToDictionary(parameters));
        }

        /// <inheritdoc cref="UnpinAsync(Expression{Func{string, object}}[])"/>
        public Task<Objects.Relationship> UnpinAsync(IDictionary<string, object> parameters)
        {
            return Tokens.AccessParameterReservedApiAsync<Objects.Relationship>(MethodType.Post, "accounts/{id}/unpin", "id", parameters);
        }
    }
}
