// Generated by TootNet.Generator.  DO NOT EDIT!

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Threading.Tasks;
using TootNet.Internal;
using TootNet.Objects;

namespace TootNet.Rest
{
    public class Markers : ApiBase
    {
        internal Markers(Tokens e) : base(e) { }

        /// <summary>
        /// <para>Get saved timeline positions.</para>
        /// <para>Available parameters:</para>
        /// <para>- <c>IEnumerable&lt;string&gt;</c> timeline (allowed values: "home", "notifications") (optional)</para>
        /// </summary>
        /// <param name="parameters">The parameters.</param>
        /// <returns>
        /// <para>The task object representing the asynchronous operation.</para>
        /// <para>The Result property on the task object returns the marker object.</para>
        /// </returns>
        public Task<Objects.Marker> GetAsync(params Expression<Func<string, object>>[] parameters)
        {
            return Tokens.AccessApiAsync<Objects.Marker>(MethodType.Get, "markers", Utils.ExpressionToDictionary(parameters));
        }

        /// <inheritdoc cref="GetAsync(Expression{Func{string, object}}[])"/>
        public Task<Objects.Marker> GetAsync(IDictionary<string, object> parameters)
        {
            return Tokens.AccessApiAsync<Objects.Marker>(MethodType.Get, "markers", parameters);
        }

        /// <summary>
        /// <para>Save your position in a timeline.</para>
        /// <para>Available parameters:</para>
        /// <para>- <c>long</c> home[last_read_id] (optional)</para>
        /// <para>- <c>long</c> notifications[last_read_id] (optional)</para>
        /// </summary>
        /// <param name="parameters">The parameters.</param>
        /// <returns>
        /// <para>The task object representing the asynchronous operation.</para>
        /// <para>The Result property on the task object returns the marker object.</para>
        /// </returns>
        public Task<Objects.Marker> PostAsync(params Expression<Func<string, object>>[] parameters)
        {
            return Tokens.AccessApiAsync<Objects.Marker>(MethodType.Post, "markers", Utils.ExpressionToDictionary(parameters));
        }

        /// <inheritdoc cref="PostAsync(Expression{Func{string, object}}[])"/>
        public Task<Objects.Marker> PostAsync(IDictionary<string, object> parameters)
        {
            return Tokens.AccessApiAsync<Objects.Marker>(MethodType.Post, "markers", parameters);
        }
    }
}
