// Generated by TootNet.Generator.  DO NOT EDIT!

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Threading.Tasks;
using TootNet.Internal;
using TootNet.Objects;

namespace TootNet.Rest
{
    public class Media : ApiBase
    {
        internal Media(Tokens e) : base(e) { }

        /// <summary>
        /// <para>Upload media as an attachment (async)</para>
        /// <para>Available parameters:</para>
        /// <para>- <c>object</c> file (required)</para>
        /// <para>- <c>object</c> thumbnail (optional)</para>
        /// <para>- <c>string</c> description (optional)</para>
        /// <para>- <c>string</c> focus (optional)</para>
        /// </summary>
        /// <param name="parameters">The parameters.</param>
        /// <returns>
        /// <para>The task object representing the asynchronous operation.</para>
        /// <para>The Result property on the task object returns the mediaattachment object.</para>
        /// </returns>
        public Task<Objects.MediaAttachment> PostAsync(params Expression<Func<string, object>>[] parameters)
        {
            return Tokens.AccessApiAsync<Objects.MediaAttachment>(MethodType.Post, "media", Utils.ExpressionToDictionary(parameters), apiVersion: "v2");
        }

        /// <inheritdoc cref="PostAsync(Expression{Func{string, object}}[])"/>
        public Task<Objects.MediaAttachment> PostAsync(IDictionary<string, object> parameters)
        {
            return Tokens.AccessApiAsync<Objects.MediaAttachment>(MethodType.Post, "media", parameters, apiVersion: "v2");
        }

        /// <summary>
        /// <para>Get media attachment</para>
        /// <para>Available parameters:</para>
        /// <para>- <c>long</c> id (required)</para>
        /// </summary>
        /// <param name="parameters">The parameters.</param>
        /// <returns>
        /// <para>The task object representing the asynchronous operation.</para>
        /// <para>The Result property on the task object returns the mediaattachment object.</para>
        /// </returns>
        public Task<Objects.MediaAttachment> IdAsync(params Expression<Func<string, object>>[] parameters)
        {
            return Tokens.AccessParameterReservedApiAsync<Objects.MediaAttachment>(MethodType.Get, "media/{id}", "id", Utils.ExpressionToDictionary(parameters));
        }

        /// <inheritdoc cref="IdAsync(Expression{Func{string, object}}[])"/>
        public Task<Objects.MediaAttachment> IdAsync(IDictionary<string, object> parameters)
        {
            return Tokens.AccessParameterReservedApiAsync<Objects.MediaAttachment>(MethodType.Get, "media/{id}", "id", parameters);
        }

        /// <summary>
        /// <para>Update media attachment</para>
        /// <para>Available parameters:</para>
        /// <para>- <c>long</c> id (required)</para>
        /// <para>- <c>object</c> thumbnail (optional)</para>
        /// <para>- <c>string</c> description (optional)</para>
        /// <para>- <c>string</c> focus (focal point: two floating points, comma-delimited) (optional)</para>
        /// </summary>
        /// <param name="parameters">The parameters.</param>
        /// <returns>
        /// <para>The task object representing the asynchronous operation.</para>
        /// <para>The Result property on the task object returns the mediaattachment object.</para>
        /// </returns>
        public Task<Objects.MediaAttachment> PutAsync(params Expression<Func<string, object>>[] parameters)
        {
            return Tokens.AccessParameterReservedApiAsync<Objects.MediaAttachment>(MethodType.Put, "media/{id}", "id", Utils.ExpressionToDictionary(parameters));
        }

        /// <inheritdoc cref="PutAsync(Expression{Func{string, object}}[])"/>
        public Task<Objects.MediaAttachment> PutAsync(IDictionary<string, object> parameters)
        {
            return Tokens.AccessParameterReservedApiAsync<Objects.MediaAttachment>(MethodType.Put, "media/{id}", "id", parameters);
        }
    }
}
