// Generated by TootNet.Generator.  DO NOT EDIT!

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Threading.Tasks;
using TootNet.Internal;
using TootNet.Objects;

namespace TootNet.Rest
{
    public class Polls : ApiBase
    {
        internal Polls(Tokens e) : base(e) { }

        /// <summary>
        /// <para>View a poll.</para>
        /// <para>Available parameters:</para>
        /// <para>- <c>long</c> id (required)</para>
        /// </summary>
        /// <param name="parameters">The parameters.</param>
        /// <returns>
        /// <para>The task object representing the asynchronous operation.</para>
        /// <para>The Result property on the task object returns the poll object.</para>
        /// </returns>
        public Task<Objects.Poll> IdAsync(params Expression<Func<string, object>>[] parameters)
        {
            return Tokens.AccessParameterReservedApiAsync<Objects.Poll>(MethodType.Get, "polls/{id}", "id", Utils.ExpressionToDictionary(parameters));
        }

        /// <inheritdoc cref="IdAsync(Expression{Func{string, object}}[])"/>
        public Task<Objects.Poll> IdAsync(IDictionary<string, object> parameters)
        {
            return Tokens.AccessParameterReservedApiAsync<Objects.Poll>(MethodType.Get, "polls/{id}", "id", parameters);
        }

        /// <summary>
        /// <para>Vote on a poll.</para>
        /// <para>Available parameters:</para>
        /// <para>- <c>long</c> id (required)</para>
        /// <para>- <c>IEnumerable&lt;int&gt;</c> choices (required)</para>
        /// </summary>
        /// <param name="parameters">The parameters.</param>
        /// <returns>
        /// <para>The task object representing the asynchronous operation.</para>
        /// <para>The Result property on the task object returns the poll object.</para>
        /// </returns>
        public Task<Objects.Poll> VotesAsync(params Expression<Func<string, object>>[] parameters)
        {
            return Tokens.AccessParameterReservedApiAsync<Objects.Poll>(MethodType.Post, "polls/{id}/votes", "id", Utils.ExpressionToDictionary(parameters));
        }

        /// <inheritdoc cref="VotesAsync(Expression{Func{string, object}}[])"/>
        public Task<Objects.Poll> VotesAsync(IDictionary<string, object> parameters)
        {
            return Tokens.AccessParameterReservedApiAsync<Objects.Poll>(MethodType.Post, "polls/{id}/votes", "id", parameters);
        }
    }
}
