// Generated by TootNet.Generator.  DO NOT EDIT!

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Threading.Tasks;
using TootNet.Internal;
using TootNet.Objects;

namespace TootNet.Rest
{
    public class Timelines : ApiBase
    {
        internal Timelines(Tokens e) : base(e) { }

        /// <summary>
        /// <para>View public timeline</para>
        /// <para>Available parameters:</para>
        /// <para>- <c>bool</c> local (optional)</para>
        /// <para>- <c>bool</c> remote (optional)</para>
        /// <para>- <c>bool</c> only_media (optional)</para>
        /// <para>- <c>long</c> max_id (optional)</para>
        /// <para>- <c>long</c> since_id (optional)</para>
        /// <para>- <c>long</c> min_id (optional)</para>
        /// <para>- <c>int</c> limit (optional)</para>
        /// </summary>
        /// <param name="parameters">The parameters.</param>
        /// <returns>
        /// <para>The task object representing the asynchronous operation.</para>
        /// <para>The Result property on the task object returns the list of status object.</para>
        /// </returns>
        public Task<Linked<Objects.Status>> PublicAsync(params Expression<Func<string, object>>[] parameters)
        {
            return Tokens.AccessApiAsync<Linked<Objects.Status>>(MethodType.Get, "timelines/public", Utils.ExpressionToDictionary(parameters));
        }

        /// <inheritdoc cref="PublicAsync(Expression{Func{string, object}}[])"/>
        public Task<Linked<Objects.Status>> PublicAsync(IDictionary<string, object> parameters)
        {
            return Tokens.AccessApiAsync<Linked<Objects.Status>>(MethodType.Get, "timelines/public", parameters);
        }

        /// <summary>
        /// <para>View hashtag timeline</para>
        /// <para>Available parameters:</para>
        /// <para>- <c>string</c> hashtag (required)</para>
        /// <para>- <c>IEnumerable&lt;string&gt;</c> any (optional)</para>
        /// <para>- <c>IEnumerable&lt;string&gt;</c> all (optional)</para>
        /// <para>- <c>IEnumerable&lt;string&gt;</c> none (optional)</para>
        /// <para>- <c>bool</c> local (optional)</para>
        /// <para>- <c>bool</c> remote (optional)</para>
        /// <para>- <c>bool</c> only_media (optional)</para>
        /// <para>- <c>long</c> max_id (optional)</para>
        /// <para>- <c>long</c> since_id (optional)</para>
        /// <para>- <c>long</c> min_id (optional)</para>
        /// <para>- <c>int</c> limit (optional)</para>
        /// </summary>
        /// <param name="parameters">The parameters.</param>
        /// <returns>
        /// <para>The task object representing the asynchronous operation.</para>
        /// <para>The Result property on the task object returns the list of status object.</para>
        /// </returns>
        public Task<Linked<Objects.Status>> TagAsync(params Expression<Func<string, object>>[] parameters)
        {
            return Tokens.AccessParameterReservedApiAsync<Linked<Objects.Status>>(MethodType.Get, "timelines/tag/{hashtag}", "hashtag", Utils.ExpressionToDictionary(parameters));
        }

        /// <inheritdoc cref="TagAsync(Expression{Func{string, object}}[])"/>
        public Task<Linked<Objects.Status>> TagAsync(IDictionary<string, object> parameters)
        {
            return Tokens.AccessParameterReservedApiAsync<Linked<Objects.Status>>(MethodType.Get, "timelines/tag/{hashtag}", "hashtag", parameters);
        }

        /// <summary>
        /// <para>View home timeline</para>
        /// <para>Available parameters:</para>
        /// <para>- <c>long</c> max_id (optional)</para>
        /// <para>- <c>long</c> since_id (optional)</para>
        /// <para>- <c>long</c> min_id (optional)</para>
        /// <para>- <c>int</c> limit (optional)</para>
        /// </summary>
        /// <param name="parameters">The parameters.</param>
        /// <returns>
        /// <para>The task object representing the asynchronous operation.</para>
        /// <para>The Result property on the task object returns the list of status object.</para>
        /// </returns>
        public Task<Linked<Objects.Status>> HomeAsync(params Expression<Func<string, object>>[] parameters)
        {
            return Tokens.AccessApiAsync<Linked<Objects.Status>>(MethodType.Get, "timelines/home", Utils.ExpressionToDictionary(parameters));
        }

        /// <inheritdoc cref="HomeAsync(Expression{Func{string, object}}[])"/>
        public Task<Linked<Objects.Status>> HomeAsync(IDictionary<string, object> parameters)
        {
            return Tokens.AccessApiAsync<Linked<Objects.Status>>(MethodType.Get, "timelines/home", parameters);
        }

        /// <summary>
        /// <para>View list timeline</para>
        /// <para>Available parameters:</para>
        /// <para>- <c>long</c> list_id (required)</para>
        /// <para>- <c>long</c> max_id (optional)</para>
        /// <para>- <c>long</c> since_id (optional)</para>
        /// <para>- <c>long</c> min_id (optional)</para>
        /// <para>- <c>int</c> limit (optional)</para>
        /// </summary>
        /// <param name="parameters">The parameters.</param>
        /// <returns>
        /// <para>The task object representing the asynchronous operation.</para>
        /// <para>The Result property on the task object returns the list of status object.</para>
        /// </returns>
        public Task<Linked<Objects.Status>> ListAsync(params Expression<Func<string, object>>[] parameters)
        {
            return Tokens.AccessParameterReservedApiAsync<Linked<Objects.Status>>(MethodType.Get, "timelines/list/{list_id}", "list_id", Utils.ExpressionToDictionary(parameters));
        }

        /// <inheritdoc cref="ListAsync(Expression{Func{string, object}}[])"/>
        public Task<Linked<Objects.Status>> ListAsync(IDictionary<string, object> parameters)
        {
            return Tokens.AccessParameterReservedApiAsync<Linked<Objects.Status>>(MethodType.Get, "timelines/list/{list_id}", "list_id", parameters);
        }
    }
}
