// Generated by TootNet.Generator.  DO NOT EDIT!

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Threading.Tasks;
using TootNet.Internal;
using TootNet.Objects;

namespace TootNet.Rest
{
    public class Trends : ApiBase
    {
        internal Trends(Tokens e) : base(e) { }

        /// <summary>
        /// <para>View trending tags</para>
        /// <para>Available parameters:</para>
        /// <para>- <c>int</c> limit (optional)</para>
        /// <para>- <c>int</c> offset (optional)</para>
        /// </summary>
        /// <param name="parameters">The parameters.</param>
        /// <returns>
        /// <para>The task object representing the asynchronous operation.</para>
        /// <para>The Result property on the task object returns the list of tag object.</para>
        /// </returns>
        public Task<IEnumerable<Objects.Tag>> TagsAsync(params Expression<Func<string, object>>[] parameters)
        {
            return Tokens.AccessApiAsync<IEnumerable<Objects.Tag>>(MethodType.Get, "trends/tags", Utils.ExpressionToDictionary(parameters));
        }

        /// <inheritdoc cref="TagsAsync(Expression{Func{string, object}}[])"/>
        public Task<IEnumerable<Objects.Tag>> TagsAsync(IDictionary<string, object> parameters)
        {
            return Tokens.AccessApiAsync<IEnumerable<Objects.Tag>>(MethodType.Get, "trends/tags", parameters);
        }

        /// <summary>
        /// <para>View trending statuses</para>
        /// <para>Available parameters:</para>
        /// <para>- <c>int</c> limit (optional)</para>
        /// <para>- <c>int</c> offset (optional)</para>
        /// </summary>
        /// <param name="parameters">The parameters.</param>
        /// <returns>
        /// <para>The task object representing the asynchronous operation.</para>
        /// <para>The Result property on the task object returns the list of status object.</para>
        /// </returns>
        public Task<IEnumerable<Objects.Status>> StatusesAsync(params Expression<Func<string, object>>[] parameters)
        {
            return Tokens.AccessApiAsync<IEnumerable<Objects.Status>>(MethodType.Get, "trends/statuses", Utils.ExpressionToDictionary(parameters));
        }

        /// <inheritdoc cref="StatusesAsync(Expression{Func{string, object}}[])"/>
        public Task<IEnumerable<Objects.Status>> StatusesAsync(IDictionary<string, object> parameters)
        {
            return Tokens.AccessApiAsync<IEnumerable<Objects.Status>>(MethodType.Get, "trends/statuses", parameters);
        }

        /// <summary>
        /// <para>View trending links</para>
        /// <para>Available parameters:</para>
        /// <para>- <c>int</c> limit (optional)</para>
        /// <para>- <c>int</c> offset (optional)</para>
        /// </summary>
        /// <param name="parameters">The parameters.</param>
        /// <returns>
        /// <para>The task object representing the asynchronous operation.</para>
        /// <para>The Result property on the task object returns the list of trendslink object.</para>
        /// </returns>
        public Task<IEnumerable<Objects.TrendsLink>> LinksAsync(params Expression<Func<string, object>>[] parameters)
        {
            return Tokens.AccessApiAsync<IEnumerable<Objects.TrendsLink>>(MethodType.Get, "trends/links", Utils.ExpressionToDictionary(parameters));
        }

        /// <inheritdoc cref="LinksAsync(Expression{Func{string, object}}[])"/>
        public Task<IEnumerable<Objects.TrendsLink>> LinksAsync(IDictionary<string, object> parameters)
        {
            return Tokens.AccessApiAsync<IEnumerable<Objects.TrendsLink>>(MethodType.Get, "trends/links", parameters);
        }
    }
}
